name: Build Container Image
run-name: Build act-runner-buildctl-kubectl 🚀
on: [push]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    container: 
      image: catthehacker/ubuntu:act-latest
    env: 
      DOCKER_CONFIG: "~/.docker/"
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # all history for all branches and tags
    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/arm64
        tags: |
          maaroen/act-runner-buildkit-kubectl:latest
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: |
          maaroen/act-runner-buildkit-kubectl:latest
