name: Build Container Image
run-name: Build act-runner-buildctl-kubectl 🚀
on: [push]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    container: 
      image: catthehacker/ubuntu:act-latest
    env: 
      DOCKER_CONFIG: "~/.docker/"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all history for all branches and tags
      - name: Install Buildkit CLI
        run: |
          wget -q "https://github.com/moby/buildkit/releases/download/v0.10.6/buildkit-v0.10.6.linux-arm64.tar.gz" \
          && mkdir buildkit \
          && cat buildkit-v0.10.6.linux-arm64.tar.gz | tar -C buildkit -zxvf - \
          && mv buildkit/bin/buildctl /usr/bin/buildctl \
          && rm -rf buildkit             
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build image
        uses: maaroen/buildkit-build-push-action@main
        with:
            platforms: 'linux/amd64,linux/arm64'
            tags: 'maaroen/act-runner-buildkit-kubectl:latest'
            buildkit-daemon-address: 'tcp://buildkitd:1234'
